apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp_v2
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        ### As alterações no argocd basicamente seriam mudar a versão 
        ### e assim acompanhar o que acontece.
        image: nanajanashia/argocd-app:1.2
        ##image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
